CREATE TABLE users
(id INT PRIMARY KEY AUTO_INCREMENT
,email VARCHAR(30) UNIQUE NOT NULL
,password VARCHAR(60) NOT NULL
,count INT DEFAULT 0
,last_login_time TIMESTAMP DEFAULT null
);

CREATE TABLE logs
(id INT PRIMARY KEY AUTO_INCREMENT
,login_time TIMESTAMP NOT NULL
,user_id INT NOT NULL
);

ALTER TABLE logs ADD CONSTRAINT fk_user_id
FOREIGN KEY (user_id) REFERENCES users(id);

